version: '3.8'

volumes:
  pgdata:
    driver: local

networks:
  my_hallo_network:
    driver: bridge

services:
  db:
    networks:
      - my_hallo_network
    env_file:
      - .env
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: 10m

  web:
    networks:
      - my_hallo_network
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db