# Generated by Django 4.2.7 on 2024-02-15 20:04

import app.recipes.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.recipes.models.upload_to_directory)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('author_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('ingredients', models.JSONField(default=list)),
                ('tools', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('category', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', slugify=app.recipes.models.custom_slugify, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
