# Generated by Django 4.2.7 on 2024-02-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('can_publish', 'Может публиковать рецепты'), ('can_unpublish', 'Может снимать рецепты с публикации')]},
        ),
    ]
