# Generated by Django 4.2.7 on 2024-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_name_alter_recipe_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
