# Generated by Django 4.2.7 on 2024-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_alter_recipe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools_json',
            field=models.JSONField(default=list),
        ),
    ]
