# Generated by Django 4.2.7 on 2024-02-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='internal_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
