# Generated by Django 4.2.7 on 2024-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_is_active_recipe_published_alter_recipe_image_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.JSONField(default=list),
        ),

    ]
