# Generated by Django 4.2.7 on 2024-02-13 21:45

import json

from django.db import migrations, models


def transfer(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.all():
        recipe.ingredients_json = [{'name': ing.name} for ing in recipe.ingredients.all()]

        steps_string = recipe.steps.replace("'", '"')
        try:
            recipe.steps_json = json.loads(steps_string)
        except json.JSONDecodeError as e:
            print(f"steps_string. Ошибка при обработке рецепта {recipe.id}: {e}")

        tools_string = recipe.tools.replace("'", '"')
        try:
            recipe.tools_json = json.loads(tools_string)
        except json.JSONDecodeError as e:
            print(f"tools_string. Ошибка при обработке рецепта {recipe.id}: {e}")

        recipe.save()


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_recipe_ingredients_json_recipe_steps_json_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer, reverse_code=migrations.RunPython.noop),
    ]
