# Generated by Django 4.2.7 on 2024-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_internal_comment_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
