# Generated by Django 4.2.7 on 2024-02-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_ingredients_json_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
