apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-content
  namespace: veg-hw
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/halloween_vegan_backend/static"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-content-claim
  namespace: veg-hw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
