apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-content
  namespace: veg-hw
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/halloween_vegan_backend/media"
  persistentVolumeReclaimPolicy: Retain
